install! 'cocoapods', :deterministic_uuids => false # add by ak fix 重复生成 ID
use_frameworks!

target 'NXFramework_Example' do
  pod 'NXFramework', :path => '../'

  target 'NXFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
